[package]
name = "term_todo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "term_todo"
path = "src/main.rs"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"